-- Drop tables if they exist
DROP TABLE IF EXISTS users;

-- Create the users table
CREATE TABLE users (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   email VARCHAR(255) UNIQUE NOT NULL,
   password VARCHAR(255) NOT NULL
);

-- Insert initial data into users table
INSERT INTO users (email, password) VALUES ('admin@example.com', 'admin123');
INSERT INTO users (email, password) VALUES ('user@example.com', 'user123');